apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-dqsinoyd
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-dqsinoyd:d667c5cfdf670c1583bb83d40bc9e90df40b9481@sha256:510a4b05d18a28e2e74e23ee9a86ca84418b062040f710bf63430670bba93320
        name: container-image  
